### ISSUE TITLE
ValueError: Namespace AppIndicator3 not available

### ISSUE THREAD

**Issue by munikarmanish** [techgaun/nepali-calendar-indicator#5]
I installed xfce4-indicator-plugin and pip requirements. And `sudo make install` ran successfully. But when I run `nepcal_applet`, I get the following error.

``` bash
Traceback (most recent call last):
  File "/usr/local/bin/nepcal_applet", line 11, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3.5/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

Did I miss something?

**Comment by techgaun** [comment]
@munikarmanish hey Manish, can you try installing gir1.2-appindicator3? I thought it was available by default but maybe not.

```
sudo apt install gir1.2-appindicator3-0.1
```

If its not available, try the autocomplete or perform apt-cache search for appindicator3. If that works, I will update the readme (or I can accept your pull request if you wanna update it)

**Comment by munikarmanish** [comment]
@techgaun Okay, finally managed to install all dependencies. **BUT**.... I only see the flag in the panel. :confused: 

![xfce-panel-screenshot](http://i.imgur.com/AkgPoaE.png)

**Comment by techgaun** [comment]
@munikarmanish oh well did you have to install `gir1.2-appindicator3-0.1`? If yes, I will put a note on readme.

Also, thats weird. didn't happen to me on xfce. What's the flavor of linux you're using? I'll see if I can make it work tomorrow. I suspect this might be due to the limitation of width available.

**Comment by munikarmanish** [comment]
I use Arch Linux and I had to install `libappindicator-gtk3` to make it run.

**Comment by techgaun** [comment]
Okay nice yeah I'll try on Arch tomorrow and see if I can get it working

**Comment by techgaun** [comment]
@munikarmanish I just got Arch installed and I can replicate the issue. Am trying to figure out how we can add the applet to indicator instead of notification area. It seems that the notification area width can not be set somehow.

Below is for my personal reference as I'm trying to play around with the :

``` shell
cat /home/techgaun/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
...
<property name="plugin-16" type="string" value="indicator">
      <property name="known-indicators" type="array">
        <value type="string" value="/home/techgaun/nepali-calendar-indicator/nepcal_applet.py"/>
      </property>
      <property name="single-row" type="bool" value="false"/>
      <property name="align-left" type="bool" value="false"/>
      <property name="blacklist" type="array">
      </property>
    </property>
...
```

Values probably need to be namespaced such as `com.canonical.indicator.bluetooth`

**Comment by diwasx** [comment]
bro, is there any way to install in arch kde?

**Comment by diwasx** [comment]
Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version


getting this error

**Comment by techgaun** [comment]
@diwasx sorry for the delay. I've not really tried it on arch kde. The warning you mention above is just a warning (although it should be fixed and I will try to fix that). What else do you get? Is it completely broken?

**Comment by diwasx** [comment]
doesnt preceed after that, it stucks there

**Comment by saidihasan** [comment]
> @munikarmanish hey Manish, can you try installing gir1.2-appindicator3? I thought it was available by default but maybe not.
> 
> ```
> sudo apt install gir1.2-appindicator3-0.1
> ```
> 
> If its not available, try the autocomplete or perform apt-cache search for appindicator3. If that works, I will update the readme (or I can accept your pull request if you wanna update it)

same case when i installing battery-monitor on ubuntu 18, this command will fix it. cheers
